version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - lowlighter
  assignees:
  - lowlighter
  ignore:
  - dependency-name: vue-prism-component
    versions:
    - 2.0.0
