version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    pull-request-branch-name:
      separator: "-"
    reviewers:
      - lowlighter
    commit_message:
      prefix: "deps"
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-patch
      - dependency-name: vue-prism-component
        versions:
          - 2.0.0
