name: GitHub metrics as SVG image
author: lowlighter
description: Generate an user's GitHub metrics as SVG image format to embed somewhere else
branding:
  icon: user-check
  color: gray-dark
inputs:
  token:
    description: GitHub Personal Token (require "public_repo" permissions)
    required: true
  user:
    description: Target GitHub username
    required: true
  filename:
    description: Name of SVG image output
    default: github-metrics.svg
  plugin_pagespeed:
    description: Enable Pagespeed metrics for user's website (requires "pagespeed_token" to be provided)
    default: no
  pagespeed_token:
    description: Pagespeed Personal Token (optional, see https://developers.google.com/speed/docs/insights/v5/get-started for more information)
  plugin_lines:
    description: Enable repositories lines metrics
    default: no
  plugin_traffic:
    description: Enable repositories traffic metrics (due to GitHub API limitations, "token" must have "repo" permissions)
    default: no
runs:
  using: node12
  main: action/dist/index.js