name: GitHub metrics as SVG image
author: lowlighter
description: Generate an user's GitHub metrics as SVG image format to embed somewhere else
branding:
  icon: user-check
  color: gray-dark
inputs:
  token:
    description: GitHub Personal Token
    required: true
  committer_token:
    description: If provided, this token will be used instead of "token" for commit operations (you can specify a bot account to avoid virtually increasing your stats due to this action commits)
    default: ""
  user:
    description: GitHub username
    default: ""
  filename:
    description: Name of SVG image output
    default: github-metrics.svg
  template:
    description: Template to use
    default: classic
  optimize:
    description: Optimize SVG image
    default: yes
  repositories:
    description: Number of repositories to use to compute metrics
    default: 100
  base:
    description: Base content to include in metrics (list of comma-separated sections name as string)
    default: "header, activity, community, repositories, metadata"
  plugin_pagespeed:
    description: Enable Google PageSpeed metrics for account attached website
    default: no
  pagespeed_token:
    description: Google Pagespeed Personal Token (*see https://developers.google.com/speed/docs/insights/v5/get-started for more informations)
    default: ""
  plugin_lines:
    description: Enable lines of code metrics
    default: no
  plugin_traffic:
    description: Enable repositories traffic metrics (*provided GitHub token require full "repo" permissions)
    default: no
  plugin_habits:
    description: Enable coding habits metrics
    default: no
  plugin_habits_from:
    description: Number of activity events to base habits on (up to 100)
    default: 100
  plugin_selfskip:
    description: Skip commits flagged with [Skip GitHub Action] from commits count
    default: no
  plugin_languages:
    description: Enable most used languages metrics
    default: no
  plugin_followup:
    description: Enable owned repositories issues and pull requests metrics
    default: no
  plugin_music:
    description: Enable music
    default: no
  plugin_music_provider:
    description: Name of the music provider you're using (*required if music plugin is enabled)
    default: ""
  plugin_music_token:
    description: Music provider personal token (*may be required depending on used provider)
    default: ""
  plugin_music_mode:
    description: Use "recent" to display recently played music and "playlist" to display tracks randomly from a given playlist (*required if music plugin is enabled)
    default: ""
  plugin_music_playlist:
    description: Embed playlist url (*required if music plugin mode is "playlist")
    default: ""
  plugin_music_limit:
    description: Number of tracks to display
    default: 4
  debug:
    description: Enable debug logs
    default: no
runs:
  using: node12
  main: action/dist/index.js