name: GitHub metrics as SVG image
author: lowlighter
description: Generate an user's GitHub metrics as SVG image format to embed somewhere else
branding:
  icon: user-check
  color: gray-dark
inputs:
  token:
    description: GitHub Personal Token (require "public_repo" permissions)
    required: true
  user:
    description: Target GitHub username
    required: true
  filename:
    description: Name of SVG image output
    default: github-metrics.svg
  pagespeed_token:
    description: Pagespeed Personal Token (optional, see https://developers.google.com/speed/docs/insights/v5/get-started for more information)
  plugins:
    description: List of additional plugins to enabled. Supported values are "lines", "pagespeed" (requires "pagespeed_token") and "traffic" (require "token" with "repository" permissions)
    default: []
runs:
  using: node12
  main: action/dist/index.js