# Repository files
repository:
  - .github/**
  - .gitignore
  - .gitattributes
  - SECURITY.md
  - LICENSE
  - CONTRIBUTING.md

# Docker
docker:
  - .dockerignore
  - Dockerfile

# Metrics source code editions
core:
  - source/app/metrics/**
action:
  - source/app/action/**
web:
  - source/app/web/**
plugins:
  - source/plugins/**
templates:
  - source/templates/**
tests:
  - source/app/mocks/**
  - tests/**
dependencies:
  - package.json
  - package-lock.json