name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install 
      run: npm ci
    - name: Build
      run: npm run build
    - name: Test
      run: npm test -- ${{ secrets.METRICS_ACTIONS_TOKEN }}
