name: Continuous integration (presets)

on:
  push:
    branches: [ presets ]

jobs:

  test:
    name: Test
    if: "!contains(github.event.head_commit.message, '[skip test]')"
    uses: lowlighter/metrics/.github/workflows/test.presets.yml@master

  publish-examples:
    name: Publish examples
    needs: [ test ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 17
      - name: Setup metrics
        run: npm ci
      - name: Run tests
        run: npm run test-presets -- publish
