name: Stale issue and pull requests

on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: This issue has been open 30 days without activity. It will be closed in 5 days if it remains inactive.
          stale-pr-message: This pull request has been open 30 days without activity. It will be closed in 5 days if it remains inactive.
          days-before-stale: 30
          days-before-close: 5
