name: Stale issue and pull requests

on:
  schedule:
    - cron: "30 1 * * *"
  workflow_dispatch:

jobs:
  stale:
    name: Flag stale issues and pull requests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: This issue seems to be inactive and will be automatically closed in a few days if it remains without any activity.
          stale-pr-message: This pull request seems to be inactive and will be automatically closed in a few days if it remains without any activity.
          days-before-stale: 21
          days-before-close: 3
          stale-issue-label: stale
          stale-pr-label: stale
          remove-stale-when-updated: yes
          operations-per-run: 100
